### ISSUE TITLE
Name clash in bower

### ISSUE THREAD

**Issue by paul-rouse** [toastal/purescript-domparser#1]
There is a name clash between this package `purescript-domparser` and [`purescript-DOMParser`](https://github.com/Fresheyeball/purescript-DOMParser) which hasn't been touched for three years.  Unfortunately, the latter one is what `bower install` finds.

I'm not sure what the best solution is - possibilities I can think of are 1)negotiate removing `purescript-DOMParser` from the bower registry, 2)rename this package, and 3)negotiate making this module part of `purescript-dom`.  In the meantime, of course, a work-around for users is referencing this repo explicitly, for example in `bower.json`:

```
  "dependencies": {
    "purescript-domparser": "https://github.com/toastal/purescript-domparser.git#^1.0.0"
  }
```

**Comment by toastal** [comment]
Good catch. I'm not actually in control of any of these pieces of software for the registry, so I don't actually know what's best to do.

**Comment by klntsky** [comment]
Rename `purescript-domparser` -> `purescript-dom-parser` maybe?

**Comment by toastal** [comment]
@8084 moved it in v4.0.0
