### ISSUE TITLE
Handle incorrect MIME types

### ISSUE THREAD

**Issue by klntsky** [toastal/purescript-domparser#5]
It is relatively easy to eliminate runtime errors like this:

```
TypeError: Argument 2 of DOMParser.parseFromString 'foo' is not a valid value for enumeration SupportedType.
```

Here are some ways to do it:

1. Wrap `parseFromString`'s result inside a `Maybe` and use `fromJust` + `unsafeFromPartial` in specialized functions.

2. Annotate `parseFromString` with `Partial` constraint and use `unsafeFromPartial` in specialized functions

3. Do not export `parseFromString` - what's the point in exposing it, if all possible usage scenarios are covered by safe functions?

**Comment by toastal** [comment]
Mostly I left it open if someone browser implemented something not covered here. Originally there was an ADT of valid types but garyb and I had considered it overkill and hard to add new types. There's no way to get the valid mime types without wrapping this in a try catch. Are you actually running into this as an issue? 

I'm not disagreeing with you that the safety would be nice, but even still, not all browsers supported SVG parsing at a time. It's sort of use at your own risk. Do you have a recommendation that actually allows passing in your own type and hoping for the best?

**Comment by klntsky** [comment]
> Are you actually running into this as an issue?

No. Moreover, I can hardly imagine a situation where it can cause actual trouble. Though I think that creating unsafe bindings sort of defeats the purpose of using PS.

> Do you have a recommendation that actually allows passing in your own type and hoping for the best?

[`Partial`](https://pursuit.purescript.org/builtins/docs/Prim#t:Partial) class is exactly for this case:

> The Partial type class is used to indicate that a function is partial, that is, it is not defined for all inputs.

Of course it still leaves out of scope runtime environments where DOMParser is not fully implemented, but perhaps this sort of incompatibilities should be handled at a lower level (e.g. by polyfills).
